# Generated by Django 5.2.3 on 2025-06-13 01:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_projectfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectfile',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='project.project'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='projectfile',
            name='attachment',
            field=models.FileField(upload_to='projectfiles'),
        ),
    ]
